import { Inter } from "next/font/google";
import "./globals.css";
import BaseGuestLayout from "../../layers/BaseGuestLayout";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, error }) {


  return (
    <html lang="en">
    <body className={inter.className}>
    <BaseGuestLayout>
      <main className="flex-1 p-6 bg-white">
        {children}
      </main>
    </BaseGuestLayout>
    </body>
    </html>
  );
}
